### PR TITLE
Use .env variable for cacheLifetimeInMinutes configuration

### PR DESCRIPTION
**Pull request by BotamicIO**
Added the `RESPONSE_CACHE_LIFETIME` environment variable to allow custom configuration through the .env file

### CODE REVIEW

**Comment by freekmurze** [comment]
Could you also make this change in the readme?

**Comment by freekmurze** [comment]
Thanks!

**Comment by vonec** [comment]
cant we have per route cache lifetime?

**Comment by freekmurze** [comment]
@vonec I'd accept a fully tested PR for that.

**Pull request merged**
